/**
 * Pure script renderer, shared by the browser UI and the `/api/setup/*`
 * route handlers (design.md D1).
 *
 * No I/O, no React, no Next.js imports, no `process.env`, no network — this
 * module must stay usable from both a browser bundle and a Node route
 * handler with byte-identical results (spec: "Identical output across both
 * paths").
 *
 * The four `.tpl` files under `src/templates/` are embedded below as
 * module-level string constants rather than read from disk with
 * `fs.readFileSync`, because that would work in a route handler but not in
 * a browser bundle (same approach as `CODEX_MODELS_TEMPLATE` in
 * `src/lib/codex.ts`). Each constant is a byte-for-byte copy of its `.tpl`
 * file's contents, generated by a one-off Node script that read the file
 * and emitted `JSON.stringify(content)` — never hand-retyped. If a `.tpl`
 * file changes, regenerate the matching constant below the same way.
 *
 * Callers MUST resolve and validate tiers, base URL, key and (for Codex)
 * provider id/name before calling any `render*` or `build*` function here
 * (see src/lib/validation.ts, src/lib/codex.ts) — this module renders
 * whatever it is given, it does not validate.
 */

import { buildCodexModelsJson } from "./codex";
import type {
  ClaudeCodeModelTier,
  CodexModelTier,
  ResolvedTiers,
} from "./validation";

/**
 * Ported, byte-for-byte, from `src/templates/claudecode-posix.sh.tpl`. Do
 * not hand-edit; regenerate from the `.tpl` file (see module header).
 */
const CLAUDECODE_POSIX_TEMPLATE: string =
  "#!/bin/sh\n# Derived from viber-router (viber-router-api/templates/setup/claudecode-linux.sh.tpl).\n# Source project license: \"Context Engine — Source-Available, Non-Commercial License,\n# Copyright (c) 2026 viber.vn. All rights reserved.\" Ported and adapted for setting_key.\n#\n# Claude Code Setup Script (macOS/Linux)\n# Auto-generated — configures Claude Code to use your endpoint and API key.\n# This script only ever creates or modifies files under ~/.claude — it never\n# touches shell startup files and never installs any package.\n\nset -e\n\nENDPOINT_URL=\"{{ENDPOINT_URL}}\"\nAPI_KEY='{{API_KEY}}'\nHAIKU_MODEL=\"{{HAIKU}}\"\nSONNET_MODEL=\"{{SONNET}}\"\nOPUS_MODEL=\"{{OPUS}}\"\nSUBAGENT_MODEL=\"{{SUBAGENT}}\"\n\nRED=$(printf '\\033[0;31m')\nGREEN=$(printf '\\033[0;32m')\nYELLOW=$(printf '\\033[1;33m')\nBLUE=$(printf '\\033[0;34m')\nNC=$(printf '\\033[0m')\n\necho \"${BLUE}================================${NC}\"\necho \"${BLUE}  Claude Code Setup${NC}\"\necho \"${BLUE}================================${NC}\"\necho \"\"\n\nif [ -z \"$ENDPOINT_URL\" ]; then\n    echo \"${RED}Error: Endpoint URL not configured${NC}\"\n    exit 1\nfi\nif [ -z \"$API_KEY\" ]; then\n    echo \"${RED}Error: API key not configured${NC}\"\n    exit 1\nfi\n\nMASKED_KEY=$(echo \"$API_KEY\" | cut -c 1-10)\necho \"Endpoint URL: ${GREEN}$ENDPOINT_URL${NC}\"\necho \"API Key:      ${GREEN}${MASKED_KEY}...${NC}\"\necho \"\"\n\n# Returns non-zero when the file exists but could not be copied (read-only dir,\n# disk full, ...). Callers must never modify a file after a failed backup.\nbackup_file() {\n    f_path=\"$1\"\n    if [ -f \"$f_path\" ]; then\n        f_backup=\"${f_path}.backup.$(date +%Y%m%d%H%M%S)\"\n        if ! cp \"$f_path\" \"$f_backup\"; then\n            echo \"${RED}  Error: could not back up $f_path${NC}\"\n            return 1\n        fi\n        echo \"${YELLOW}  Backed up: $f_path -> $f_backup${NC}\"\n    fi\n    return 0\n}\n\n# Claude Code reads ANTHROPIC_* and CLAUDE_CODE_SUBAGENT_MODEL from the current\n# process environment, and those take precedence over ~/.claude/settings.json.\n# This script never unsets or modifies them — it only warns, because doing\n# anything else would mean writing to files outside ~/.claude.\n# Passing \"${VAR+x}\" (rather than checking the value) means a variable set to\n# an empty string still counts as \"set\", matching Claude Code's own behavior.\nACTIVE_VARS=\"\"\nnote_active_var() {\n    if [ -n \"$2\" ]; then\n        ACTIVE_VARS=\"$ACTIVE_VARS $1\"\n    fi\n}\n\nnote_active_var ANTHROPIC_BASE_URL \"${ANTHROPIC_BASE_URL+x}\"\nnote_active_var ANTHROPIC_AUTH_TOKEN \"${ANTHROPIC_AUTH_TOKEN+x}\"\nnote_active_var ANTHROPIC_API_KEY \"${ANTHROPIC_API_KEY+x}\"\nnote_active_var ANTHROPIC_DEFAULT_HAIKU_MODEL \"${ANTHROPIC_DEFAULT_HAIKU_MODEL+x}\"\nnote_active_var ANTHROPIC_DEFAULT_SONNET_MODEL \"${ANTHROPIC_DEFAULT_SONNET_MODEL+x}\"\nnote_active_var ANTHROPIC_DEFAULT_OPUS_MODEL \"${ANTHROPIC_DEFAULT_OPUS_MODEL+x}\"\nnote_active_var CLAUDE_CODE_SUBAGENT_MODEL \"${CLAUDE_CODE_SUBAGENT_MODEL+x}\"\n\nif [ -n \"$ACTIVE_VARS\" ]; then\n    echo \"${YELLOW}Warning: these variables are set in your current environment:${NC}\"\n    for var_name in $ACTIVE_VARS; do\n        echo \"${YELLOW}  - $var_name${NC}\"\n    done\n    echo \"${YELLOW}They override ~/.claude/settings.json for any Claude Code process that inherits them.${NC}\"\n    echo \"${YELLOW}To remove them for future sessions, delete the lines that export them from${NC}\"\n    echo \"${YELLOW}wherever your shell sets environment variables on startup, then open a new terminal.${NC}\"\n    echo \"${YELLOW}To clear them in this session only, run: unset$ACTIVE_VARS${NC}\"\n    echo \"\"\nfi\n\nCLAUDE_DIR=\"$HOME/.claude\"\nSETTINGS_FILE=\"$CLAUDE_DIR/settings.json\"\n\nupdate_settings_json() {\n    mkdir -p \"$CLAUDE_DIR\"\n\n    if ! command -v jq >/dev/null 2>&1; then\n        echo \"\"\n        echo \"${RED}Error: jq is required but not installed.${NC}\"\n        echo \"\"\n        echo \"Please install jq first:\"\n        echo \"  ${BLUE}macOS:${NC}         brew install jq\"\n        echo \"  ${BLUE}Ubuntu/Debian:${NC} sudo apt-get install -y jq\"\n        echo \"  ${BLUE}Fedora/RHEL:${NC}   sudo dnf install -y jq\"\n        echo \"  ${BLUE}Arch Linux:${NC}    sudo pacman -S jq\"\n        echo \"\"\n        echo \"Then run this script again.\"\n        exit 1\n    fi\n\n    merge_base=\"$SETTINGS_FILE\"\n    merge_base_is_temp=0\n\n    if [ -f \"$SETTINGS_FILE\" ]; then\n        if ! backup_file \"$SETTINGS_FILE\"; then\n            exit 1\n        fi\n\n        if [ ! -s \"$SETTINGS_FILE\" ] || ! jq empty \"$SETTINGS_FILE\" >/dev/null 2>&1; then\n            f_backup=$(ls -t \"${SETTINGS_FILE}.backup.\"* 2>/dev/null | head -n 1)\n            echo \"${YELLOW}  Warning: existing settings.json could not be parsed as JSON.${NC}\"\n            echo \"${YELLOW}  Previous content preserved at: $f_backup${NC}\"\n            echo \"${YELLOW}  Writing a fresh settings.json with only the generated keys.${NC}\"\n            merge_base=$(mktemp)\n            merge_base_is_temp=1\n            echo '{}' > \"$merge_base\"\n        fi\n    else\n        echo '{}' > \"$SETTINGS_FILE\"\n    fi\n\n    tmp_file=$(mktemp)\n    if ! jq --arg url \"$ENDPOINT_URL\" --arg key \"$API_KEY\" \\\n       --arg haiku \"$HAIKU_MODEL\" --arg sonnet \"$SONNET_MODEL\" --arg opus \"$OPUS_MODEL\" \\\n       --arg subagent \"$SUBAGENT_MODEL\" '\n        .env.ANTHROPIC_BASE_URL = $url |\n        .env.ANTHROPIC_AUTH_TOKEN = $key |\n        .env.ANTHROPIC_DEFAULT_HAIKU_MODEL = $haiku |\n        .env.ANTHROPIC_DEFAULT_SONNET_MODEL = $sonnet |\n        .env.ANTHROPIC_DEFAULT_OPUS_MODEL = $opus |\n        .env.CLAUDE_CODE_SUBAGENT_MODEL = $subagent |\n        .disableLoginPrompt = true |\n        .includeCoAuthoredBy = false\n    ' \"$merge_base\" > \"$tmp_file\"; then\n        echo \"${RED}  Error: failed to generate settings.json${NC}\"\n        rm -f \"$tmp_file\"\n        if [ \"$merge_base_is_temp\" = \"1\" ]; then\n            rm -f \"$merge_base\"\n        fi\n        exit 1\n    fi\n    mv \"$tmp_file\" \"$SETTINGS_FILE\"\n    if [ \"$merge_base_is_temp\" = \"1\" ]; then\n        rm -f \"$merge_base\"\n    fi\n}\n\necho \"${BLUE}Configuring Claude Code settings...${NC}\"\nupdate_settings_json\necho \"  ${GREEN}✓ Updated ~/.claude/settings.json${NC}\"\n\necho \"\"\necho \"${GREEN}================================${NC}\"\necho \"${GREEN}  Configuration Complete!${NC}\"\necho \"${GREEN}================================${NC}\"\necho \"\"\necho \"Claude Code is now configured:\"\necho \"  Endpoint: ${BLUE}$ENDPOINT_URL${NC}\"\necho \"  API Key:  ${BLUE}${MASKED_KEY}...${NC}\"\necho \"  Config:   ${BLUE}~/.claude/settings.json${NC}\"\necho \"\"\nif [ -n \"$ACTIVE_VARS\" ]; then\n    echo \"${YELLOW}Reminder: variables set in this environment still override settings.json — see warning above.${NC}\"\n    echo \"\"\nfi\necho \"${YELLOW}Next steps:${NC}\"\necho \"  1. Open a new terminal if you changed any environment variables\"\necho \"  2. Run: ${BLUE}claude${NC}\"\necho \"\"\n";

/**
 * Ported, byte-for-byte, from `src/templates/claudecode-windows.ps1.tpl`.
 * Do not hand-edit; regenerate from the `.tpl` file (see module header).
 */
const CLAUDECODE_WINDOWS_TEMPLATE: string =
  "# Derived from viber-router (viber-router-api/templates/setup/claudecode-windows.ps1.tpl).\n# Source project license: \"Context Engine — Source-Available, Non-Commercial License,\n# Copyright (c) 2026 viber.vn. All rights reserved.\" Ported and adapted for setting_key.\n#\n# Claude Code Setup Script (Windows PowerShell 5.1+)\n# Auto-generated — configures Claude Code to use your endpoint and API key.\n# This script only ever creates or modifies files under ~/.claude — it never\n# creates or changes a User or Machine environment variable and never installs\n# any package.\n\n$ErrorActionPreference = \"Stop\"\n\n$ENDPOINT_URL = \"{{ENDPOINT_URL}}\"\n$API_KEY = '{{API_KEY}}'\n$HAIKU_MODEL = \"{{HAIKU}}\"\n$SONNET_MODEL = \"{{SONNET}}\"\n$OPUS_MODEL = \"{{OPUS}}\"\n$SUBAGENT_MODEL = \"{{SUBAGENT}}\"\n\nWrite-Host \"================================\" -ForegroundColor Blue\nWrite-Host \"  Claude Code Setup\" -ForegroundColor Blue\nWrite-Host \"================================\" -ForegroundColor Blue\nWrite-Host \"\"\n\nif ([string]::IsNullOrEmpty($ENDPOINT_URL)) {\n    Write-Host \"Error: Endpoint URL not configured\" -ForegroundColor Red\n    exit 1\n}\nif ([string]::IsNullOrEmpty($API_KEY)) {\n    Write-Host \"Error: API key not configured\" -ForegroundColor Red\n    exit 1\n}\n\n$MASKED_KEY = $API_KEY.Substring(0, [Math]::Min(10, $API_KEY.Length))\nWrite-Host \"Endpoint URL: \" -NoNewline\nWrite-Host \"$ENDPOINT_URL\" -ForegroundColor Green\nWrite-Host \"API Key:      \" -NoNewline\nWrite-Host \"$MASKED_KEY...\" -ForegroundColor Green\nWrite-Host \"\"\n\n# Claude Code reads ANTHROPIC_* and CLAUDE_CODE_SUBAGENT_MODEL from the current\n# process environment, and those take precedence over settings.json. This\n# script never creates, changes or removes a User or Machine environment\n# variable — it only warns, because doing otherwise would mean touching\n# something outside the Claude Code config directory.\n# Test-Path against the Env: drive is used (rather than checking the value)\n# so a variable set to an empty string still counts as \"set\".\n$WATCHED_VARS = @(\n    \"ANTHROPIC_BASE_URL\",\n    \"ANTHROPIC_AUTH_TOKEN\",\n    \"ANTHROPIC_API_KEY\",\n    \"ANTHROPIC_DEFAULT_HAIKU_MODEL\",\n    \"ANTHROPIC_DEFAULT_SONNET_MODEL\",\n    \"ANTHROPIC_DEFAULT_OPUS_MODEL\",\n    \"CLAUDE_CODE_SUBAGENT_MODEL\"\n)\n\n$activeVars = @()\nforeach ($varName in $WATCHED_VARS) {\n    if (Test-Path \"Env:\\$varName\") {\n        $activeVars += $varName\n    }\n}\n\nif ($activeVars.Count -gt 0) {\n    Write-Host \"Warning: these variables are set in your current environment:\" -ForegroundColor Yellow\n    foreach ($varName in $activeVars) {\n        Write-Host \"  - $varName\" -ForegroundColor Yellow\n    }\n    Write-Host \"They override settings.json for any Claude Code process that inherits them.\" -ForegroundColor Yellow\n    Write-Host \"To remove one permanently, delete it from wherever it is configured (System\" -ForegroundColor Yellow\n    Write-Host \"Properties > Environment Variables, or however it was set) and open a new terminal.\" -ForegroundColor Yellow\n    Write-Host \"To clear them in this session only, run:\" -ForegroundColor Yellow\n    foreach ($varName in $activeVars) {\n        Write-Host \"  Remove-Item Env:\\$varName\" -ForegroundColor Yellow\n    }\n    Write-Host \"\"\n}\n\n$settingsDir = Join-Path $HOME \".claude\"\n$settingsPath = Join-Path $settingsDir \"settings.json\"\n\nif (-not (Test-Path $settingsDir)) {\n    New-Item -ItemType Directory -Path $settingsDir -Force | Out-Null\n}\n\nWrite-Host \"Configuring Claude Code settings...\" -ForegroundColor Blue\n\n$settings = $null\n\nif (Test-Path $settingsPath) {\n    $backupPath = \"$settingsPath.backup.$(Get-Date -Format 'yyyyMMddHHmmss')\"\n    try {\n        Copy-Item $settingsPath $backupPath -ErrorAction Stop\n    } catch {\n        Write-Host \"Error: could not back up $settingsPath\" -ForegroundColor Red\n        Write-Host \"  $($_.Exception.Message)\" -ForegroundColor Red\n        exit 1\n    }\n    Write-Host \"  Backed up: $settingsPath -> $backupPath\" -ForegroundColor Yellow\n\n    $parseFailed = $false\n    $isEmpty = (Get-Item $settingsPath).Length -eq 0\n    if (-not $isEmpty) {\n        try {\n            $content = Get-Content $settingsPath -Raw -ErrorAction Stop\n            $settings = ConvertFrom-Json $content -ErrorAction Stop\n        } catch {\n            $parseFailed = $true\n        }\n    } else {\n        $parseFailed = $true\n    }\n\n    if ($parseFailed -or $null -eq $settings) {\n        Write-Host \"  Warning: existing settings.json could not be parsed as JSON.\" -ForegroundColor Yellow\n        Write-Host \"  Previous content preserved at: $backupPath\" -ForegroundColor Yellow\n        Write-Host \"  Writing a fresh settings.json with only the generated keys.\" -ForegroundColor Yellow\n        $settings = $null\n    }\n}\n\nif ($null -eq $settings) {\n    $settings = New-Object PSObject\n}\n\nif (-not (Get-Member -InputObject $settings -Name \"env\" -MemberType Properties)) {\n    $settings | Add-Member -MemberType NoteProperty -Name \"env\" -Value (New-Object PSObject)\n}\n\n$envVars = @{\n    \"ANTHROPIC_BASE_URL\" = $ENDPOINT_URL\n    \"ANTHROPIC_AUTH_TOKEN\" = $API_KEY\n    \"ANTHROPIC_DEFAULT_HAIKU_MODEL\" = $HAIKU_MODEL\n    \"ANTHROPIC_DEFAULT_SONNET_MODEL\" = $SONNET_MODEL\n    \"ANTHROPIC_DEFAULT_OPUS_MODEL\" = $OPUS_MODEL\n    \"CLAUDE_CODE_SUBAGENT_MODEL\" = $SUBAGENT_MODEL\n}\n\nforeach ($kvp in $envVars.GetEnumerator()) {\n    if (Get-Member -InputObject $settings.env -Name $kvp.Key -MemberType Properties) {\n        $settings.env.($kvp.Key) = $kvp.Value\n    } else {\n        $settings.env | Add-Member -MemberType NoteProperty -Name $kvp.Key -Value $kvp.Value\n    }\n}\n\nif (Get-Member -InputObject $settings -Name \"disableLoginPrompt\" -MemberType Properties) {\n    $settings.disableLoginPrompt = $true\n} else {\n    $settings | Add-Member -MemberType NoteProperty -Name \"disableLoginPrompt\" -Value $true\n}\n\nif (Get-Member -InputObject $settings -Name \"includeCoAuthoredBy\" -MemberType Properties) {\n    $settings.includeCoAuthoredBy = $false\n} else {\n    $settings | Add-Member -MemberType NoteProperty -Name \"includeCoAuthoredBy\" -Value $false\n}\n\n$jsonContent = $settings | ConvertTo-Json -Depth 10\n[System.IO.File]::WriteAllText($settingsPath, $jsonContent, [System.Text.UTF8Encoding]::new($false))\n\nWrite-Host \"  \" -NoNewline\nWrite-Host \"OK\" -ForegroundColor Green -NoNewline\nWrite-Host \" Updated $settingsPath\"\n\nWrite-Host \"\"\nWrite-Host \"================================\" -ForegroundColor Green\nWrite-Host \"  Configuration Complete!\" -ForegroundColor Green\nWrite-Host \"================================\" -ForegroundColor Green\nWrite-Host \"\"\nWrite-Host \"Claude Code is now configured:\"\nWrite-Host \"  Endpoint: \" -NoNewline\nWrite-Host \"$ENDPOINT_URL\" -ForegroundColor Blue\nWrite-Host \"  API Key:  \" -NoNewline\nWrite-Host \"$MASKED_KEY...\" -ForegroundColor Blue\nWrite-Host \"  Config:   \" -NoNewline\nWrite-Host \"$settingsPath\" -ForegroundColor Blue\nWrite-Host \"\"\nif ($activeVars.Count -gt 0) {\n    Write-Host \"Reminder: variables set in this environment still override settings.json - see warning above.\" -ForegroundColor Yellow\n    Write-Host \"\"\n}\nWrite-Host \"Next steps:\" -ForegroundColor Yellow\nWrite-Host \"  1. Open a new terminal if you changed any environment variables\"\nWrite-Host \"  2. Run: \" -NoNewline\nWrite-Host \"claude\" -ForegroundColor Blue\nWrite-Host \"\"\n";

/**
 * Ported, byte-for-byte, from `src/templates/codex-posix.sh.tpl`. Do not
 * hand-edit; regenerate from the `.tpl` file (see module header).
 */
const CODEX_POSIX_TEMPLATE: string =
  "#!/bin/sh\n# Derived from viber-router (viber-router-api/templates/setup/codex-linux.sh.tpl).\n# Source project license: \"Context Engine — Source-Available, Non-Commercial License,\n# Copyright (c) 2026 viber.vn. All rights reserved.\" Ported and adapted for setting_key.\n#\n# Codex CLI Setup Script (macOS/Linux)\n# Auto-generated — configures the Codex CLI to use your endpoint and API key.\n# This script only ever creates or modifies files under ~/.codex — it never\n# installs, upgrades or removes the Codex CLI or any package.\n\nset -e\n\nENDPOINT_URL=\"{{ENDPOINT_URL}}\"\nAPI_KEY='{{API_KEY}}'\nCODEX_SMALL=\"{{SMALL}}\"\nCODEX_MEDIUM=\"{{MEDIUM}}\"\nCODEX_LARGE=\"{{LARGE}}\"\nPROVIDER_ID=\"{{PROVIDER_ID}}\"\nPROVIDER_NAME=\"{{PROVIDER_NAME}}\"\n\nRED=$(printf '\\033[0;31m')\nGREEN=$(printf '\\033[0;32m')\nYELLOW=$(printf '\\033[1;33m')\nBLUE=$(printf '\\033[0;34m')\nNC=$(printf '\\033[0m')\n\necho \"${BLUE}================================${NC}\"\necho \"${BLUE}  Codex CLI Setup${NC}\"\necho \"${BLUE}================================${NC}\"\necho \"\"\n\nif [ -z \"$ENDPOINT_URL\" ]; then\n    echo \"${RED}Error: Endpoint URL not configured${NC}\"\n    exit 1\nfi\nif [ -z \"$API_KEY\" ]; then\n    echo \"${RED}Error: API key not configured${NC}\"\n    exit 1\nfi\nif [ -z \"$CODEX_SMALL\" ] || [ -z \"$CODEX_MEDIUM\" ] || [ -z \"$CODEX_LARGE\" ]; then\n    echo \"${RED}Error: model tiers not configured${NC}\"\n    exit 1\nfi\nif [ -z \"$PROVIDER_ID\" ]; then\n    echo \"${RED}Error: provider id not configured${NC}\"\n    exit 1\nfi\n\nMASKED_KEY=$(echo \"$API_KEY\" | cut -c 1-10)\necho \"Endpoint URL:      ${GREEN}$ENDPOINT_URL${NC}\"\necho \"API Key:           ${GREEN}${MASKED_KEY}...${NC}\"\necho \"Small (Fast):      ${GREEN}$CODEX_SMALL${NC}\"\necho \"Medium (Default):  ${GREEN}$CODEX_MEDIUM${NC}\"\necho \"Large (Powerful):  ${GREEN}$CODEX_LARGE${NC}\"\necho \"\"\n\nif ! command -v codex >/dev/null 2>&1; then\n    echo \"${YELLOW}Warning: the Codex CLI was not found on PATH.${NC}\"\n    echo \"${YELLOW}Configuration files will still be written; install the Codex CLI separately when ready.${NC}\"\n    echo \"\"\nfi\n\nCODEX_DIR=\"$HOME/.codex\"\nmkdir -p \"$CODEX_DIR\"\n\necho \"${BLUE}Configuring Codex CLI...${NC}\"\n\n# config.toml and models.json fully describe the provider setup, so they are\n# backed up and written whole rather than merged.\nif [ -f \"$CODEX_DIR/config.toml\" ]; then\n    CONFIG_BACKUP=\"$CODEX_DIR/config.toml.backup.$(date +%Y%m%d%H%M%S)\"\n    if ! cp \"$CODEX_DIR/config.toml\" \"$CONFIG_BACKUP\"; then\n        echo \"${RED}  Error: could not back up $CODEX_DIR/config.toml${NC}\"\n        exit 1\n    fi\n    echo \"${YELLOW}  Backed up: $CODEX_DIR/config.toml -> $CONFIG_BACKUP${NC}\"\nfi\n\ncat > \"$CODEX_DIR/config.toml\" << TOML_EOF\nmodel = \"$CODEX_MEDIUM\"\nmodel_provider = \"$PROVIDER_ID\"\nmodel_catalog_json = \"~/.codex/models.json\"\n\n[model_providers.$PROVIDER_ID]\nname = \"$PROVIDER_NAME\"\nbase_url = \"$ENDPOINT_URL\"\nexperimental_bearer_token = \"$API_KEY\"\nwire_api = \"responses\"\n\n[features]\napps = false\nTOML_EOF\necho \"  ${GREEN}✓ Written ~/.codex/config.toml${NC}\"\n\n# models.json content is rendered server-side from a template with the\n# {{SMALL}}/{{MEDIUM}}/{{LARGE}} slots already substituted; it is embedded\n# here as static JSON.\ncat > \"$CODEX_DIR/models.json\" << 'MODELS_EOF'\n{{MODELS_JSON}}\nMODELS_EOF\necho \"  ${GREEN}✓ Written ~/.codex/models.json${NC}\"\n\n# auth.json holds Codex login state this tool has no business touching, so it\n# is written only when missing or empty.\nif [ ! -f \"$CODEX_DIR/auth.json\" ] || [ ! -s \"$CODEX_DIR/auth.json\" ]; then\n    echo '{}' > \"$CODEX_DIR/auth.json\"\n    echo \"  ${GREEN}✓ Written ~/.codex/auth.json${NC}\"\nelse\n    echo \"  ${GREEN}✓ Kept existing ~/.codex/auth.json${NC}\"\nfi\n\n# models_cache.json is Codex's own cache of the previous model catalog; if left\n# behind it can shadow the models.json just written, so remove it when present.\nif [ -f \"$CODEX_DIR/models_cache.json\" ]; then\n    rm -f \"$CODEX_DIR/models_cache.json\"\n    echo \"  ${GREEN}✓ Removed ~/.codex/models_cache.json${NC}\"\nfi\n\necho \"\"\necho \"${GREEN}================================${NC}\"\necho \"${GREEN}  Configuration Complete!${NC}\"\necho \"${GREEN}================================${NC}\"\necho \"\"\necho \"Codex CLI is now configured:\"\necho \"  Endpoint:          ${BLUE}$ENDPOINT_URL${NC}\"\necho \"  API Key:           ${BLUE}${MASKED_KEY}...${NC}\"\necho \"  Small (Fast):      ${BLUE}$CODEX_SMALL${NC}\"\necho \"  Medium (Default):  ${BLUE}$CODEX_MEDIUM${NC}\"\necho \"  Large (Powerful):  ${BLUE}$CODEX_LARGE${NC}\"\necho \"\"\necho \"${YELLOW}Next steps:${NC}\"\necho \"  Run: ${BLUE}codex${NC}\"\necho \"\"\n";

/**
 * Ported, byte-for-byte, from `src/templates/codex-windows.ps1.tpl`. Do not
 * hand-edit; regenerate from the `.tpl` file (see module header).
 */
const CODEX_WINDOWS_TEMPLATE: string =
  "# Derived from viber-router (viber-router-api/templates/setup/codex-windows.ps1.tpl).\n# Source project license: \"Context Engine — Source-Available, Non-Commercial License,\n# Copyright (c) 2026 viber.vn. All rights reserved.\" Ported and adapted for setting_key.\n#\n# Codex CLI Setup Script (Windows PowerShell 5.1+)\n# Auto-generated — configures the Codex CLI to use your endpoint and API key.\n# This script only ever creates or modifies files under ~/.codex — it never\n# installs, upgrades or removes the Codex CLI or any package.\n\n$ErrorActionPreference = \"Stop\"\n\n$ENDPOINT_URL = \"{{ENDPOINT_URL}}\"\n$API_KEY = '{{API_KEY}}'\n$CODEX_SMALL = \"{{SMALL}}\"\n$CODEX_MEDIUM = \"{{MEDIUM}}\"\n$CODEX_LARGE = \"{{LARGE}}\"\n$PROVIDER_ID = \"{{PROVIDER_ID}}\"\n$PROVIDER_NAME = \"{{PROVIDER_NAME}}\"\n\nWrite-Host \"================================\" -ForegroundColor Blue\nWrite-Host \"  Codex CLI Setup\" -ForegroundColor Blue\nWrite-Host \"================================\" -ForegroundColor Blue\nWrite-Host \"\"\n\nif ([string]::IsNullOrEmpty($ENDPOINT_URL)) {\n    Write-Host \"Error: Endpoint URL not configured\" -ForegroundColor Red\n    exit 1\n}\nif ([string]::IsNullOrEmpty($API_KEY)) {\n    Write-Host \"Error: API key not configured\" -ForegroundColor Red\n    exit 1\n}\nif ([string]::IsNullOrEmpty($CODEX_SMALL) -or [string]::IsNullOrEmpty($CODEX_MEDIUM) -or [string]::IsNullOrEmpty($CODEX_LARGE)) {\n    Write-Host \"Error: model tiers not configured\" -ForegroundColor Red\n    exit 1\n}\nif ([string]::IsNullOrEmpty($PROVIDER_ID)) {\n    Write-Host \"Error: provider id not configured\" -ForegroundColor Red\n    exit 1\n}\n\n$MASKED_KEY = $API_KEY.Substring(0, [Math]::Min(10, $API_KEY.Length))\nWrite-Host \"Endpoint URL:      \" -NoNewline\nWrite-Host \"$ENDPOINT_URL\" -ForegroundColor Green\nWrite-Host \"API Key:           \" -NoNewline\nWrite-Host \"$MASKED_KEY...\" -ForegroundColor Green\nWrite-Host \"Small (Fast):      \" -NoNewline\nWrite-Host \"$CODEX_SMALL\" -ForegroundColor Green\nWrite-Host \"Medium (Default):  \" -NoNewline\nWrite-Host \"$CODEX_MEDIUM\" -ForegroundColor Green\nWrite-Host \"Large (Powerful):  \" -NoNewline\nWrite-Host \"$CODEX_LARGE\" -ForegroundColor Green\nWrite-Host \"\"\n\n$codexCmd = Get-Command codex -ErrorAction SilentlyContinue\nif (-not $codexCmd) {\n    Write-Host \"Warning: the Codex CLI was not found on PATH.\" -ForegroundColor Yellow\n    Write-Host \"Configuration files will still be written; install the Codex CLI separately when ready.\" -ForegroundColor Yellow\n    Write-Host \"\"\n}\n\n$codexDir = Join-Path $HOME \".codex\"\nif (-not (Test-Path $codexDir)) {\n    New-Item -ItemType Directory -Path $codexDir -Force | Out-Null\n}\n\nWrite-Host \"Configuring Codex CLI...\" -ForegroundColor Blue\n\n# config.toml and models.json fully describe the provider setup, so they are\n# backed up and written whole rather than merged.\n$configPath = Join-Path $codexDir \"config.toml\"\nif (Test-Path $configPath) {\n    $configBackupPath = \"$configPath.backup.$(Get-Date -Format 'yyyyMMddHHmmss')\"\n    try {\n        Copy-Item $configPath $configBackupPath -ErrorAction Stop\n    } catch {\n        Write-Host \"Error: could not back up $configPath\" -ForegroundColor Red\n        Write-Host \"  $($_.Exception.Message)\" -ForegroundColor Red\n        exit 1\n    }\n    Write-Host \"  Backed up: $configPath -> $configBackupPath\" -ForegroundColor Yellow\n}\n\n$configContent = @\"\nmodel = \"$CODEX_MEDIUM\"\nmodel_provider = \"$PROVIDER_ID\"\nmodel_catalog_json = \"~/.codex/models.json\"\n\n[model_providers.$PROVIDER_ID]\nname = \"$PROVIDER_NAME\"\nbase_url = \"$ENDPOINT_URL\"\nexperimental_bearer_token = \"$API_KEY\"\nwire_api = \"responses\"\n\n[features]\napps = false\n\"@\n[System.IO.File]::WriteAllText($configPath, $configContent, [System.Text.UTF8Encoding]::new($false))\nWrite-Host \"  \" -NoNewline\nWrite-Host \"OK\" -ForegroundColor Green -NoNewline\nWrite-Host \" Written config.toml\"\n\n# models.json content is rendered server-side from a template with the\n# {{SMALL}}/{{MEDIUM}}/{{LARGE}} slots already substituted; it is embedded\n# here as static JSON (single-quoted here-string, no variable expansion).\n$modelsPath = Join-Path $codexDir \"models.json\"\n$modelsContent = @'\n{{MODELS_JSON}}\n'@\n[System.IO.File]::WriteAllText($modelsPath, $modelsContent, [System.Text.UTF8Encoding]::new($false))\nWrite-Host \"  \" -NoNewline\nWrite-Host \"OK\" -ForegroundColor Green -NoNewline\nWrite-Host \" Written models.json\"\n\n# auth.json holds Codex login state this tool has no business touching, so it\n# is written only when missing or empty.\n$authPath = Join-Path $codexDir \"auth.json\"\nif ((-not (Test-Path $authPath)) -or (Get-Item $authPath).Length -eq 0) {\n    [System.IO.File]::WriteAllText($authPath, \"{}\", [System.Text.UTF8Encoding]::new($false))\n    Write-Host \"  \" -NoNewline\n    Write-Host \"OK\" -ForegroundColor Green -NoNewline\n    Write-Host \" Written auth.json\"\n} else {\n    Write-Host \"  \" -NoNewline\n    Write-Host \"OK\" -ForegroundColor Green -NoNewline\n    Write-Host \" Kept existing auth.json\"\n}\n\n# models_cache.json is Codex's own cache of the previous model catalog; if left\n# behind it can shadow the models.json just written, so remove it when present.\n$modelsCachePath = Join-Path $codexDir \"models_cache.json\"\nif (Test-Path $modelsCachePath) {\n    Remove-Item $modelsCachePath -Force\n    Write-Host \"  \" -NoNewline\n    Write-Host \"OK\" -ForegroundColor Green -NoNewline\n    Write-Host \" Removed models_cache.json\"\n}\n\nWrite-Host \"\"\nWrite-Host \"================================\" -ForegroundColor Green\nWrite-Host \"  Configuration Complete!\" -ForegroundColor Green\nWrite-Host \"================================\" -ForegroundColor Green\nWrite-Host \"\"\nWrite-Host \"Codex CLI is now configured:\"\nWrite-Host \"  Endpoint:          \" -NoNewline\nWrite-Host \"$ENDPOINT_URL\" -ForegroundColor Blue\nWrite-Host \"  API Key:           \" -NoNewline\nWrite-Host \"$MASKED_KEY...\" -ForegroundColor Blue\nWrite-Host \"  Small (Fast):      \" -NoNewline\nWrite-Host \"$CODEX_SMALL\" -ForegroundColor Blue\nWrite-Host \"  Medium (Default):  \" -NoNewline\nWrite-Host \"$CODEX_MEDIUM\" -ForegroundColor Blue\nWrite-Host \"  Large (Powerful):  \" -NoNewline\nWrite-Host \"$CODEX_LARGE\" -ForegroundColor Blue\nWrite-Host \"\"\nWrite-Host \"Next steps:\" -ForegroundColor Yellow\nWrite-Host \"  Run: \" -NoNewline\nWrite-Host \"codex\" -ForegroundColor Blue\nWrite-Host \"\"\n";

/**
 * `true` when `os`, compared case-insensitively, is `windows` or `win`;
 * `false` for any other value, including `undefined` (spec: "OS-specific
 * script rendering" — POSIX is the default).
 */
export function isWindows(os: string | undefined): boolean {
  if (os === undefined) {
    return false;
  }
  const normalized = os.toLowerCase();
  return normalized === "windows" || normalized === "win";
}

/**
 * Regex matching a `{{VAR}}` placeholder, where `VAR` is the uppercase
 * `[A-Z_]+` grammar used by every `.tpl` file in `src/templates/`.
 */
const PLACEHOLDER_PATTERN = /\{\{([A-Z_]+)\}\}/g;

/**
 * Substitutes every `{{VAR}}` placeholder in `template` with `vars[VAR]`.
 *
 * Uses a replacer *function* rather than a replacement string. `String
 * .prototype.replace` interprets sequences like `$&`, `` $` `` and `$1` in
 * a *string* replacement; a replacer function's return value is inserted
 * literally with no such interpretation. `provider_name` and the rendered
 * `{{MODELS_JSON}}` body are not charset-restricted (unlike the key and
 * model names, which validation.ts already confines to `[A-Za-z0-9._:-]`),
 * so a value containing `$` is a real, reachable input here — not a
 * theoretical one.
 *
 * Throws if the template references a placeholder with no matching entry
 * in `vars`, so a renamed or newly added `.tpl` placeholder fails loudly
 * instead of silently leaking `{{...}}` into the rendered script.
 */
export function renderScript(
  template: string,
  vars: Record<string, string>,
): string {
  return template.replace(PLACEHOLDER_PATTERN, (_match, name: string) => {
    if (!Object.prototype.hasOwnProperty.call(vars, name)) {
      throw new Error(
        `renderScript: no value provided for placeholder {{${name}}}`,
      );
    }
    return vars[name];
  });
}

/** Input to {@link renderClaudeCodeScript}. */
export interface ClaudeCodeScriptInput {
  /** Selects the Windows PowerShell template when set (see {@link isWindows}); POSIX otherwise. */
  os?: string;
  /** Normalized `base_url` (see `normalizeBaseUrl`). */
  endpointUrl: string;
  /** Validated API key (see `validateApiKey`). */
  apiKey: string;
  /**
   * The fully resolved and validated haiku/sonnet/opus tiers — the result
   * of `validateResolvedTiers(resolveModelTiers(...))`.
   */
  resolvedTiers: ResolvedTiers<ClaudeCodeModelTier>;
  /**
   * The resolved subagent model — the result of
   * `resolveSubagentModel(resolvedTiers, subagentTier)`.
   */
  subagentModel: string;
}

/**
 * Renders the finished Claude Code install script for one OS from
 * validated input (spec: "OS-specific script rendering").
 */
export function renderClaudeCodeScript(input: ClaudeCodeScriptInput): string {
  const template = isWindows(input.os)
    ? CLAUDECODE_WINDOWS_TEMPLATE
    : CLAUDECODE_POSIX_TEMPLATE;
  return renderScript(template, {
    ENDPOINT_URL: input.endpointUrl,
    API_KEY: input.apiKey,
    HAIKU: input.resolvedTiers.haiku,
    SONNET: input.resolvedTiers.sonnet,
    OPUS: input.resolvedTiers.opus,
    SUBAGENT: input.subagentModel,
  });
}

/** Input to {@link renderCodexScript}. */
export interface CodexScriptInput {
  /** Selects the Windows PowerShell template when set (see {@link isWindows}); POSIX otherwise. */
  os?: string;
  /** Normalized `base_url` (see `normalizeBaseUrl`). */
  endpointUrl: string;
  /** Validated API key (see `validateApiKey`). */
  apiKey: string;
  /**
   * The fully resolved and validated small/medium/large tiers — the
   * result of `validateResolvedTiers(resolveModelTiers(...))`.
   */
  resolvedTiers: ResolvedTiers<CodexModelTier>;
  /** Validated Codex provider id (see `validateProviderId`). */
  providerId: string;
  /** Provider display name. */
  providerName: string;
}

/**
 * Renders the finished Codex install script for one OS from validated
 * input (spec: "OS-specific script rendering"). The `{{MODELS_JSON}}`
 * placeholder is filled with the fully-rendered catalog text from
 * `buildCodexModelsJson` before substitution, per the templates' rendering
 * contract (it is pasted into a single-quoted POSIX heredoc and a
 * single-quoted PowerShell here-string, so it must already be finished,
 * literal text — no further templating happens once it is inside them).
 */
export function renderCodexScript(input: CodexScriptInput): string {
  const template = isWindows(input.os)
    ? CODEX_WINDOWS_TEMPLATE
    : CODEX_POSIX_TEMPLATE;
  const modelsJson = buildCodexModelsJson({
    resolvedTiers: input.resolvedTiers,
  });
  return renderScript(template, {
    ENDPOINT_URL: input.endpointUrl,
    API_KEY: input.apiKey,
    SMALL: input.resolvedTiers.small,
    MEDIUM: input.resolvedTiers.medium,
    LARGE: input.resolvedTiers.large,
    PROVIDER_ID: input.providerId,
    PROVIDER_NAME: input.providerName,
    MODELS_JSON: modelsJson,
  });
}

/** Input to {@link renderCombinedScript}. */
export interface CombinedScriptInput {
  /** Selects the Windows PowerShell templates when set (see {@link isWindows}); POSIX otherwise. */
  os?: string;
  /**
   * Present when the user selected Claude Code as an install target.
   * Absent (not merely falsy — omit the key or pass `undefined`) means
   * Claude Code was deselected and MUST contribute nothing to the
   * combined script.
   */
  claudeCode?: Omit<ClaudeCodeScriptInput, "os">;
  /**
   * Present when the user selected Codex as an install target. Absent
   * means Codex was deselected and MUST contribute nothing to the
   * combined script.
   */
  codex?: Omit<CodexScriptInput, "os">;
}

/**
 * Composes the install script for every *selected* target into one script
 * for a single OS.
 *
 * A deselected target (its input omitted) contributes nothing — no
 * heading, no variables, no trailing separator. This was a real bug in
 * the design prototype: the combined script and the one-liner always
 * emitted Claude Code even when only Codex was selected. Each per-target
 * body already starts with its own shebang / `$ErrorActionPreference`
 * line; when two bodies are concatenated, the second occurrence of either
 * is harmless (a `#!` after line 1 is just a POSIX comment, and
 * re-assigning `$ErrorActionPreference` to the same value in PowerShell is
 * a no-op), so no further de-duplication is needed.
 */
export function renderCombinedScript(input: CombinedScriptInput): string {
  const { os, claudeCode, codex } = input;
  const parts: string[] = [];
  if (claudeCode) {
    parts.push(renderClaudeCodeScript({ ...claudeCode, os }));
  }
  if (codex) {
    parts.push(renderCodexScript({ ...codex, os }));
  }
  return parts.join("\n\n");
}

/**
 * Path of the Claude Code one-line installer route (spec: "One-line
 * installer route handlers"). Batch G's `GET` handler must be mounted at
 * this exact path.
 */
export const CLAUDECODE_SETUP_PATH = "/api/setup/claudecode";

/**
 * Path of the Codex one-line installer route (spec: "One-line installer
 * route handlers"). Batch G's `GET` handler must be mounted at this exact
 * path.
 */
export const CODEX_SETUP_PATH = "/api/setup/codex";

/**
 * Query parameter names accepted by `GET /api/setup/claudecode`. Batch G's
 * route handler MUST read exactly these names; this UI/one-liner side and
 * that route handler side must never drift.
 */
export interface ClaudeCodeOneLinerParams {
  /** Validated API key. */
  key: string;
  /** Normalized `base_url`. */
  base_url: string;
  /** Selects the rendered OS (see {@link isWindows}); omit for POSIX. */
  os?: string;
  /** Resolved haiku-tier model. */
  haiku: string;
  /** Resolved sonnet-tier model. */
  sonnet: string;
  /** Resolved opus-tier model. */
  opus: string;
  /** Resolved subagent model (one of the three tier values above). */
  subagent: string;
}

/**
 * Query parameter names accepted by `GET /api/setup/codex`. Batch G's
 * route handler MUST read exactly these names; this UI/one-liner side and
 * that route handler side must never drift.
 */
export interface CodexOneLinerParams {
  /** Validated API key. */
  key: string;
  /** Normalized `base_url`. */
  base_url: string;
  /** Selects the rendered OS (see {@link isWindows}); omit for POSIX. */
  os?: string;
  /** Resolved small-tier model. */
  small: string;
  /** Resolved medium-tier model. */
  medium: string;
  /** Resolved large-tier model. */
  large: string;
  /** Validated Codex provider id. */
  provider_id: string;
  /** Provider display name. */
  provider_name: string;
}

/** Builds a `?`-free query string from a flat string param object, omitting any `undefined` value. */
function buildQueryString(params: object): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params) as Array<
    [string, string | undefined]
  >) {
    if (value !== undefined) {
      search.set(key, value);
    }
  }
  return search.toString();
}

/**
 * Builds the full one-line-installer URL for the Claude Code target,
 * carrying every tier override and the resolved subagent model (spec:
 * "Client-side full script as the recommended path" — the one-liner must
 * produce the same configuration as the full script). `origin` is
 * supplied by the caller (e.g. `window.location.origin` in the browser)
 * rather than read here, keeping this module free of browser globals.
 */
export function buildClaudeCodeOneLinerUrl(
  origin: string,
  params: ClaudeCodeOneLinerParams,
): string {
  return `${origin}${CLAUDECODE_SETUP_PATH}?${buildQueryString(params)}`;
}

/**
 * Builds the full one-line-installer URL for the Codex target, carrying
 * every tier override plus `provider_id` / `provider_name` (spec:
 * "Client-side full script as the recommended path"). `origin` is
 * supplied by the caller rather than read here.
 */
export function buildCodexOneLinerUrl(
  origin: string,
  params: CodexOneLinerParams,
): string {
  return `${origin}${CODEX_SETUP_PATH}?${buildQueryString(params)}`;
}

/** Wraps a one-liner URL in the platform-appropriate fetch-and-run command. */
export function buildOneLinerCommand(url: string, os?: string): string {
  return isWindows(os)
    ? `irm "${url}" | iex`
    : `curl -fsSL "${url}" | sh`;
}

/** Input to {@link buildCombinedOneLiner}. */
export interface CombinedOneLinerInput {
  origin: string;
  os?: string;
  /** Present when Claude Code is a selected target; absent means it contributes nothing. */
  claudeCode?: Omit<ClaudeCodeOneLinerParams, "os">;
  /** Present when Codex is a selected target; absent means it contributes nothing. */
  codex?: Omit<CodexOneLinerParams, "os">;
}

/**
 * Composes the one-line install command for every *selected* target,
 * mirroring {@link renderCombinedScript}: a deselected target contributes
 * nothing. When both targets are selected, one command per target is
 * emitted, newline-separated, since each fetches from a different route.
 */
export function buildCombinedOneLiner(input: CombinedOneLinerInput): string {
  const { origin, os, claudeCode, codex } = input;
  const lines: string[] = [];
  if (claudeCode) {
    const url = buildClaudeCodeOneLinerUrl(origin, { ...claudeCode, os });
    lines.push(buildOneLinerCommand(url, os));
  }
  if (codex) {
    const url = buildCodexOneLinerUrl(origin, { ...codex, os });
    lines.push(buildOneLinerCommand(url, os));
  }
  return lines.join("\n");
}

/**
 * Every rendered template body, keyed by its source `.tpl` file — exposed
 * for tests that must assert "no unreplaced `{{...}}` placeholder remains"
 * against all four templates, not just one (tasks.md 6.3).
 */
export const ALL_SCRIPT_TEMPLATES: Readonly<Record<string, string>> = {
  "claudecode-posix.sh.tpl": CLAUDECODE_POSIX_TEMPLATE,
  "claudecode-windows.ps1.tpl": CLAUDECODE_WINDOWS_TEMPLATE,
  "codex-posix.sh.tpl": CODEX_POSIX_TEMPLATE,
  "codex-windows.ps1.tpl": CODEX_WINDOWS_TEMPLATE,
};
